// <auto-generated />
using System;
using EduGestor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduGestor.Migrations
{
    [DbContext(typeof(EduGestorContext))]
    [Migration("20260518011947_FixRegistrationRequireds")]
    partial class FixRegistrationRequireds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduGestor.Models.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Workload")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("EduGestor.Models.DisciplineClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("StudentClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("DisciplineClasses");
                });

            modelBuilder.Entity("EduGestor.Models.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bimester")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DisciplineClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<float>("Frequency")
                        .HasPrecision(5, 2)
                        .HasColumnType("real");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SchoolYear")
                        .HasColumnType("integer");

                    b.Property<float>("StudentGrade")
                        .HasPrecision(5, 2)
                        .HasColumnType("real");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineClassId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("EduGestor.Models.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("EduGestor.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EduGestor.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("GuardianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EduGestor.Models.StudentClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Series")
                        .HasColumnType("integer");

                    b.Property<int>("Shift")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentClasses");
                });

            modelBuilder.Entity("EduGestor.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EduGestor.Models.DisciplineClass", b =>
                {
                    b.HasOne("EduGestor.Models.Discipline", "Discipline")
                        .WithMany("DisciplineClasses")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduGestor.Models.StudentClass", "StudentClass")
                        .WithMany("DisciplineClasses")
                        .HasForeignKey("StudentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduGestor.Models.Teacher", "Teacher")
                        .WithMany("DisciplineClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("StudentClass");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduGestor.Models.Grade", b =>
                {
                    b.HasOne("EduGestor.Models.DisciplineClass", "DisciplineClass")
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EduGestor.Models.Discipline", null)
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineId");

                    b.HasOne("EduGestor.Models.Registration", "Registration")
                        .WithMany("Grades")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EduGestor.Models.Student", null)
                        .WithMany("Grades")
                        .HasForeignKey("StudentId");

                    b.Navigation("DisciplineClass");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("EduGestor.Models.Registration", b =>
                {
                    b.HasOne("EduGestor.Models.StudentClass", "StudentClass")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduGestor.Models.Student", "Student")
                        .WithMany("Registrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("EduGestor.Models.Student", b =>
                {
                    b.HasOne("EduGestor.Models.Guardian", "Guardian")
                        .WithMany("Students")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("EduGestor.Models.Discipline", b =>
                {
                    b.Navigation("DisciplineClasses");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("EduGestor.Models.DisciplineClass", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("EduGestor.Models.Guardian", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EduGestor.Models.Registration", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("EduGestor.Models.Student", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EduGestor.Models.StudentClass", b =>
                {
                    b.Navigation("DisciplineClasses");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("EduGestor.Models.Teacher", b =>
                {
                    b.Navigation("DisciplineClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
